### ISSUE TITLE
unable to retrieve db system vnic id

### ISSUE THREAD

**Issue by pierrepgithub** [oracle/fmw-kubernetes#211]
The following command output is null:
vnic=$(oci db system get --db-system-id $DBSYSTEMID --query 'data."scan-ip-ids"[0]' --raw-output)

I tried running the same oci command against the db system outside of the provision_oke.sh script, and it is null:

"scan-ip-ids": null

This being null stops the ./provision_oke.sh script from continuing as the next step is to: "Step 203 : Setting Up Passwordless Authentication for the OS 'oracle' User..."

And without the IP address of the vnic, it cannot set it up..

This is from the logs:
ssh -q -i /home/opc/.ssh/id_rsa -t -o 'StrictHostKeyChecking no' -o ProxyCommand='ssh -q -i /home/opc/.ssh/id_rsa opc@xx.xx.xx.xx -W %h:%p' opc@Error:

Notice the: "opc:Error:"

**Comment by pierrepgithub** [comment]
I think the vnic needs to be queried from the db node, not the db system?

For example:
1) Get DB Node VNIC OCID
oci db node list --compartment-id <compartment-ocid> --db-system-id <db-system-ocid> --raw-output --query 'data[0]."vnic-id"'
2) Get IP Address from VNIC
oci network vnic get --vnic-id <db-node-vnic-ocid> --query 'data."private-ip"' --raw-output

**Comment by solanki-chetan** [comment]
Can i please have the output of 
oci db system get --db-system-id $DBSYSTEMID --query 'data."scan-ip-ids"[0]' --raw-output
The value of DBSYSTEMID would be in the output/oci_oke.ocid

**Comment by pierrepgithub** [comment]
> Can i please have the output of oci db system get --db-system-id $DBSYSTEMID --query 'data."scan-ip-ids"[0]' --raw-output The value of DBSYSTEMID would be in the output/oci_oke.ocid

Hello, yea I said in the original message:
"The following command output is null:
vnic=$(oci db system get --db-system-id $DBSYSTEMID --query 'data."scan-ip-ids"[0]' --raw-output)

I tried running the same oci command against the db system outside of the provision_oke.sh script, and it is null:

"scan-ip-ids": null"

I ran the 'oci db system get --db-system-id $DBSYSTEMID --query 'data."scan-ip-ids"[0]' --raw-output' command in my compute instance and it was null

I also ran the oci command without the query, and the scan-ip-ids was null
