### ISSUE TITLE
missing the /xbusrouting/images/route.gif

### ISSUE THREAD

**Issue by wenjian80** [oracle/fmw-kubernetes#41]
in https://github.com/oracle/fmw-kubernetes/blob/master/OracleSOASuite/kubernetes/ingress-per-domain/templates/traefik-ingress.yaml

it is missing the /xbusrouting/images/route.gif, some gif cannot be shown in the servicebus console.

**Comment by sbattagi** [comment]
Issue will be fixed in release 21.1.2.
