### ISSUE TITLE
Issue in generating the SOA domain 

### ISSUE THREAD

**Issue by Jayakrishnanj0404** [oracle/fmw-kubernetes#44]
create-domain.sh fails with the following error.

Generating ./weblogic-domains/geasoa/create-domain-job.yaml
Generating ./weblogic-domains/geasoa/delete-domain-job.yaml
Generating ./weblogic-domains/geasoa/domain.yaml
Checking to see if the secret geasoa-domain-credentials exists in namespace geasoa-ns
[ERROR] The domain secret geasoa-domain-credentials in namespace geasoa-ns does contain a username
[ERROR] The domain secret geasoa-domain-credentials in namespace geasoa-ns does contain a password
[ERROR] The errors listed above must be resolved before the script can continue

**Comment by ashageetha** [comment]
Hi @Jayakrishnanj0404 ,

Please confirm the Docker and Kubernetes Version.
Execute "kubectl version" (on terminal where "create-domain.sh" is executed) and confirm the Kubernetes Client and Server Versions.

For list of supported versions refer:  "[System requirements for Oracle SOA Suite domains](https://oracle.github.io/fmw-kubernetes/soa-domains/installguide/prerequisites/#system-requirements-for-oracle-soa-suite-domains)".

Thanks,
Asha
