### ISSUE TITLE
soa_21.3.2: Getting error durin git clone

### ISSUE THREAD

**Issue by sy1968** [oracle/fmw-kubernetes#72]
following https://oracle.github.io/fmw-kubernetes/soa-domains/installguide/prepare-your-environment/#set-up-the-code-repository-to-deploy-oracle-soa-suite-domains

git clone https://github.com/oracle/fmw-kubernetes.git --branch release/21.3.2

Cloning into 'fmw-kubernetes'...
fatal: Remote branch release/21.3.2 not found in upstream origin
Unexpected end of command stream

--Earlier versions of clones are working fine.

**Comment by vivek-sam** [comment]
The Clone of the new 21.3.2 release was confirmed to be working. 
git clone https://github.com/oracle/fmw-kubernetes.git --branch release/21.3.2

Please reopen if you are still facing the same problem.
